config/routes.rb
Rails.application.routes.draw do
  get "contact", to: "contacts#new"
  get 'contacts/create'
  get "about", to: "about#index"

  namespace :admin do
    get "login", to: "sessions#new"
    post "login", to: "sessions#create"
    delete "logout", to: "sessions#destroy"
  end

  namespace :admin do
    get 'users/index'
    get 'users/show'
    get 'users/new'
    get 'users/create'
    get 'users/edit'
    get 'users/update'
    get 'users/destroy'
  end
  namespace :admin do
    get 'comments/destroy'
  end
  get 'comments/new'
  namespace :admin do
    get 'categories/index'
    get 'categories/show'
    get 'categories/new'
    get 'categories/create'
    get 'categories/edit'
    get 'categories/update'
    get 'categories/destroy'
  end
  get 'categories/show'
  namespace :admin do
    get 'posts/new'
    get 'posts/create'
    get 'posts/edit'
    get 'posts/update'
    get 'posts/destroy'
    get 'posts/index'
    get 'posts/show'
  end
  get 'posts/index'
  get 'posts/show'

  root "posts#index"

  resources :posts, :categories
  resources :contacts, only: [:new, :create]
  namespace :admin do
    resources :posts, :categories, :comments, :users, :sessions
  end

  resources :posts do
    resources :comments
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts
  validates :name, presence: true

  def self.search(query)
    where("name like ?", "%#{query}%")
    #code
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :posts, required: false
  validates :name, presence: true
  validates :email, presence: true
  validates :body, presence: true
  validates :post_id, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :category
  belongs_to :user
  has_many :comments
  has_attached_file :image, default_url: ":style/rails1.jpg"
  validates_attachment_content_type :image, content_type:  /\Aimage\/.*\Z/
  validates :title, presence: true
  validates :category_id, presence: true
  validates :body, presence: true

  def self.search(query)
    where("title like ? OR body like ?", "%#{query}%", "%#{query}")
    #code
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  has_secure_password

  def self.search(query)
    where("name like ? OR email like ?", "%#{query}%", "%#{query}")
    #code
  end

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
    @categories = Category.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def index
    #code
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find(params[:id])
    @categories = Category.all
    @posts = @category.posts.all
  end

  def index
    @categories = Category.all
    #code
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
  	@post = Post.find(params[:post_id])
  	@comment = @post.comments.build(comment_params)
    @comment.save

  	flash[:notice] ='Comment Added'

  	redirect_to post_path(@post)
  end

  private
  	def comment_params
  		params.require(:comment).permit(:name, :email, :body, :post_id)
  	end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @categories = Category.all
  end

  def create
  end

  def index
    @categories = Category.all
    #code
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @categories = Category.all
    if params[:search]
      @posts = Post.search(params[:search]).all.order("created_at DESC").paginate(per_page: 2, page: params[:page])
    else
      @posts = Post.all.order("created_at DESC").paginate(per_page: 2, page: params[:page])
    end
  end

  def show
    @post = Post.find(params[:id])
    @categories = Category.all
    @comment = Comment.new
    @comments = Comment.all
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rblog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'admin/application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'admin/application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
      <%= link_to "rBlog", root_path, class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to "Posts", admin_posts_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Categories", admin_categories_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Users", admin_users_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <p class="nav-link"><%= "Logged in as #{current_user.name}" %></p>
          </li>
          <li class="nav-item">
            <%= link_to "Log out", admin_logout_path, method: :delete, class: "nav-link" %>
          </li>
        </ul>
        <%= render "partials/admin/search" %>
        <!-- <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
          <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
        </form> -->
      </div>
    </nav>
    <br /><br /><br /><br />
    <section>
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <% if flash[:notice] %>
              <div class="alert alert-success">
                <%= flash[:notice] %>
              </div>
            <% end %>

            <% if flash[:alert] %>
              <div class="alert alert-danger">
                <%= flash[:alert] %>
              </div>
            <% end %>

            <%= yield %>
          </div>
        </div>
      </div>
    </section>

    <%= render "partials/footer" %>

    <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="js/bootstrap.js"></script> -->


  </body>
</html>

app/views/layouts/admin/login.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Login | Rblog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'admin/login', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'admin/application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/partials/_comments.html.erb
<!-- Comments -->
<div class="comments">
  <h2 class="page-header"><%= @post.comments.length %> Comments</h2>
  <% @post.comments.each do |comment| %>
  <div class="comment">
    <div class="row">
      <div class="col-md-2">
        <%= image_tag("user.jpg") %>
      </div>
      <div class="col-md-10">
        <div class="card">
          <div class="card-body">
            <h4><%= comment.name %><span>/<%= comment.created_at.to_time.strftime('%B %e at %l:%M %p') %></span></h4>
            <%= comment.body %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <% end %>

  <div class="card add-comment">
    <div class="card-body">
      <h2 class="page-header">Add Comment</h2>
      <%= form_for([@post, @post.comments.build]) do |f| %>

        <div class="form-group">
          <%= f.label :name %><br>
          <%= f.text_field :name, class:'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :email %><br>
          <%= f.text_field :email, class:'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :body %><br>
          <%= f.text_area :body, class:'form-control' %>
        </div>
         <div class="form-group">
          <%= f.submit "Submit", class:'btn btn-primary' %>
        </div>
    <% end %>
    </div>
  </div>
</div>

app/views/partials/_footer.html.erb
<footer>
  <p>Copyright &copy; 2018, rBlog | <%= link_to "Admin Login", admin_login_path %></p>
</footer>

app/views/partials/_search.html.erb
<%= form_tag(posts_path, method: :get, id: "search-form", class: "form-inline my-2 my-lg-0") do %>
  <div class="form-group">
    <%= text_field_tag :search, params[:search], placeholder: "Search Posts", class: "form-control mr-sm-2" %>
  </div>
  <%= submit_tag "Search", name: nil, class: "btn btn-secondary my-2 my-sm-0" %>
<% end %>

app/views/partials/_sidebar.html.erb
<div class="list-group">
  <% @categories.each do |category| %>
    <%= link_to category.name, category_path(category), class: "list-group-item" %>
  <% end %>
</div>

app/views/partials/admin/_search.html.erb
<% if params[:controller] == "admin/posts" %>
  <%= form_tag(admin_posts_path, method: :get, id: "search-form", class: "form-inline my-2 my-lg-0") do %>
    <div class="form-group">
      <%= text_field_tag :search, params[:search], placeholder: "Search Posts", class: "form-control mr-sm-2" %>
    </div>
    <%= submit_tag "Search", name: nil, class: "btn btn-secondary my-2 my-sm-0" %>
  <% end %>
<% elsif params[:controller] == "admin/categories" %>
  <%= form_tag(admin_categories_path, method: :get, id: "search-form", class: "form-inline my-2 my-lg-0") do %>
    <div class="form-group">
      <%= text_field_tag :search, params[:search], placeholder: "Search Categories", class: "form-control mr-sm-2" %>
    </div>
    <%= submit_tag "Search", name: nil, class: "btn btn-secondary my-2 my-sm-0" %>
  <% end %>
<% elsif params[:controller] == "admin/users" %>
  <%= form_tag(admin_users_path, method: :get, id: "search-form", class: "form-inline my-2 my-lg-0") do %>
    <div class="form-group">
      <%= text_field_tag :search, params[:search], placeholder: "Search Users", class: "form-control mr-sm-2" %>
    </div>
    <%= submit_tag "Search", name: nil, class: "btn btn-secondary my-2 my-sm-0" %>
  <% end %>
<% end %>