config/routes.rb
Rails.application.routes.draw do
  get "contact", to: "contacts#new"
  get 'contacts/create'
  get "about", to: "about#index"

  namespace :admin do
    get "login", to: "sessions#new"
    post "login", to: "sessions#create"
    delete "logout", to: "sessions#destroy"
  end

  namespace :admin do
    get 'users/index'
    get 'users/show'
    get 'users/new'
    get 'users/create'
    get 'users/edit'
    get 'users/update'
    get 'users/destroy'
  end
  namespace :admin do
    get 'comments/destroy'
  end
  get 'comments/new'
  namespace :admin do
    get 'categories/index'
    get 'categories/show'
    get 'categories/new'
    get 'categories/create'
    get 'categories/edit'
    get 'categories/update'
    get 'categories/destroy'
  end
  get 'categories/show'
  namespace :admin do
    get 'posts/new'
    get 'posts/create'
    get 'posts/edit'
    get 'posts/update'
    get 'posts/destroy'
    get 'posts/index'
    get 'posts/show'
  end
  get 'posts/index'
  get 'posts/show'

  root "posts#index"

  resources :posts, :categories
  resources :contacts, only: [:new, :create]
  namespace :admin do
    resources :posts, :categories, :comments, :users, :sessions
  end

  resources :posts do
    resources :comments
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts
  validates :name, presence: true

  def self.search(query)
    where("name like ?", "%#{query}%")
    #code
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::ApplicationController
  def index
    if params[:search]
      @categories = Category.search(params[:search]).all.order("created_at DESC").paginate(per_page: 10, page: params[:page])
    else
      @categories = Category.all.order("created_at DESC").paginate(per_page: 10, page: params[:page])
    end
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @page_title = "Add new category"
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Category created"
      redirect_to admin_categories_path
    else
      render "new"
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:notice] = "Category updated"
      redirect_to admin_categories_path
    else
      render "edit"
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    flash[:notice] = "Category deleted"
    redirect_to admin_categories_path
  end

  private
    def category_params
      params.require(:category).permit(:name)
      #code
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find(params[:id])
    @categories = Category.all
    @posts = @category.posts.all
  end

  def index
    @categories = Category.all
    #code
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/edit.html.erb
<h2>Edit category</h2>

<%= form_for [:admin, @category] do |f| %>
  <% if @category.errors.any? %>
    <% @category.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger">
        <%= msg %>
      </div>
    <% end %>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <%= f.submit "Submit", class: "btn btn-primary" %>
  <%= link_to "Cancel", admin_categories_path, class: "btn btn-default" %>
<% end %>

app/views/admin/categories/index.html.erb
<div class="card card-body bg-light">
  <h2 class="page-header">Manage categories <%= link_to "Add new", new_admin_category_path, class: "btn btn-success pull-right" %></h2>
  <table class="table table-striped">
    <tr>
      <th>Category title</th>
      <th>Date created</th>
      <th>Actions</th>
    </tr>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.created_at.to_date %></td>
        <td><%= link_to "Edit", edit_admin_category_path(category), class: "btn btn-primary" %> <%= link_to "Delete", admin_category_path(category), class: "btn btn-danger", method: :delete, data: {confirm: "Are you sure?"} %></td>
      </tr>
    <% end %>
  </table>
  <div class="digg_pagination">
    <%= will_paginate @posts %>
  </div>
  </div>

app/views/admin/categories/new.html.erb
<h2>Add new category</h2>

<%= form_for [:admin, @category] do |f| %>
  <% if @category.errors.any? %>
    <% @category.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger">
        <%= msg %>
      </div>
    <% end %>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <%= f.submit "Submit", class: "btn btn-primary" %>
  <%= link_to "Cancel", admin_categories_path, class: "btn btn-default" %>
<% end %>