config/routes.rb
Rails.application.routes.draw do
  get "contact", to: "contacts#new"
  get 'contacts/create'
  get "about", to: "about#index"

  namespace :admin do
    get "login", to: "sessions#new"
    post "login", to: "sessions#create"
    delete "logout", to: "sessions#destroy"
  end

  namespace :admin do
    get 'users/index'
    get 'users/show'
    get 'users/new'
    get 'users/create'
    get 'users/edit'
    get 'users/update'
    get 'users/destroy'
  end
  namespace :admin do
    get 'comments/destroy'
  end
  get 'comments/new'
  namespace :admin do
    get 'categories/index'
    get 'categories/show'
    get 'categories/new'
    get 'categories/create'
    get 'categories/edit'
    get 'categories/update'
    get 'categories/destroy'
  end
  get 'categories/show'
  namespace :admin do
    get 'posts/new'
    get 'posts/create'
    get 'posts/edit'
    get 'posts/update'
    get 'posts/destroy'
    get 'posts/index'
    get 'posts/show'
  end
  get 'posts/index'
  get 'posts/show'

  root "posts#index"

  resources :posts, :categories
  resources :contacts, only: [:new, :create]
  namespace :admin do
    resources :posts, :categories, :comments, :users, :sessions
  end

  resources :posts do
    resources :comments
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts
  validates :name, presence: true

  def self.search(query)
    where("name like ?", "%#{query}%")
    #code
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :posts, required: false
  validates :name, presence: true
  validates :email, presence: true
  validates :body, presence: true
  validates :post_id, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :category
  belongs_to :user
  has_many :comments
  has_attached_file :image, default_url: ":style/rails1.jpg"
  validates_attachment_content_type :image, content_type:  /\Aimage\/.*\Z/
  validates :title, presence: true
  validates :category_id, presence: true
  validates :body, presence: true

  def self.search(query)
    where("title like ? OR body like ?", "%#{query}%", "%#{query}")
    #code
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  has_secure_password

  def self.search(query)
    where("name like ? OR email like ?", "%#{query}%", "%#{query}")
    #code
  end

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
    @categories = Category.all
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController
  def index
    if params[:search]
      @users = User.search(params[:search]).all.order("created_at DESC").paginate(per_page: 10, page: params[:page])
    else
      @users = User.all.order("created_at DESC").paginate(per_page: 10, page: params[:page])
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @page_title = "Add new user"
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "User created"
      redirect_to admin_users_path
    else
      render "new"
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "User updated"
      redirect_to admin_users_path
    else
      render "edit"
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:notice] = "User deleted"
    redirect_to admin_users_path
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
      #code
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def index
    #code
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find(params[:id])
    @categories = Category.all
    @posts = @category.posts.all
  end

  def index
    @categories = Category.all
    #code
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
  	@post = Post.find(params[:post_id])
  	@comment = @post.comments.build(comment_params)
    @comment.save

  	flash[:notice] ='Comment Added'

  	redirect_to post_path(@post)
  end

  private
  	def comment_params
  		params.require(:comment).permit(:name, :email, :body, :post_id)
  	end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @categories = Category.all
  end

  def create
  end

  def index
    @categories = Category.all
    #code
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @categories = Category.all
    if params[:search]
      @posts = Post.search(params[:search]).all.order("created_at DESC").paginate(per_page: 2, page: params[:page])
    else
      @posts = Post.all.order("created_at DESC").paginate(per_page: 2, page: params[:page])
    end
  end

  def show
    @post = Post.find(params[:id])
    @categories = Category.all
    @comment = Comment.new
    @comments = Comment.all
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
    #code
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
    #code
  end

  def verify_logged_in
    unless current_user
      redirect_to admin_login_path
    end
    #code
  end

  def log_out
    session[:user_id] = nil
    @current_user = nil
    #code
  end

  def is_logged_in?
    !session[:user_id].nil?
    #code
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/users/edit.html.erb
<h2>Edit User</h2>

<%= form_for [:admin, @user] do |f| %>
	<!-- Check for errors -->
	<% if @user.errors.any? %>
	    <% @user.errors.full_messages.each do |msg| %>
	    	<!-- Show errors -->
	      	<div class="alert alert-danger"><%= msg %></div>
	    <% end %>
  	<% end %>

	<div class="form-group">
		<%= f.label :name %>
		<%= f.text_field :name ,class:'form-control' %>
	</div>

  <div class="form-group">
		<%= f.label :email %>
		<%= f.text_field :email ,class:'form-control' %>
	</div>

  <div class="form-group">
		<%= f.label :password %>
		<%= f.password_field :password ,class:'form-control' %>
	</div>

  <div class="form-group">
		<%= f.label :password_confirmation %>
		<%= f.password_field :password_confirmation ,class:'form-control' %>
	</div>

	<br>
	<%= f.submit "Submit", class:'btn btn-primary' %>
	<%=link_to "Cancel", admin_users_path, class:'btn btn-default' %>
<% end %>

app/views/admin/users/index.html.erb
<div class="card card-body bg-light">
  <h2 class="page-header">Manage users
    <%= link_to "Add new User", new_admin_user_path, class: "btn btn-success" %>
  </h2>
  <% if @users.exists? %>
    <table class="table table-striped">
      <tr>
        <th>User name</th>
        <th>User email</th>
        <th>Date created</th>
        <th>Actions</th>
      </tr>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.name %></td>
          <td><%= user.email %></td>
          <td><%= user.created_at.to_date %></td>
          <td>
            <%= link_to "Edit", edit_admin_user_path(user), class: "btn btn-primary" %>
            <%= link_to "Delete", admin_user_path(user), class: "btn btn-danger", method: :delete, data: {confirm: "Are you sure?"} %>
          </td>
        </tr>
      <% end %>
    </table>
    <div class="digg_pagination">
      <%= will_paginate @posts %>
    </div>
  <% else %>
    <p>There are no users to show.</p>
  <% end %>
</div>

app/views/admin/users/new.html.erb
<h2>Add New User</h2>

<%= form_for [:admin, @user] do |f| %>
	<!-- Check for errors -->
	<% if @user.errors.any? %>
	    <% @user.errors.full_messages.each do |msg| %>
	    	<!-- Show errors -->
	      	<div class="alert alert-danger"><%= msg %></div>
	    <% end %>
  	<% end %>

	<div class="form-group">
		<%= f.label :name %>
		<%= f.text_field :name ,class:'form-control' %>
	</div>

  <div class="form-group">
		<%= f.label :email %>
		<%= f.text_field :email ,class:'form-control' %>
	</div>

  <div class="form-group">
		<%= f.label :password %>
		<%= f.password_field :password ,class:'form-control' %>
	</div>

  <div class="form-group">
		<%= f.label :password_confirmation %>
		<%= f.password_field :password_confirmation ,class:'form-control' %>
	</div>

	<br>
	<%= f.submit "Submit", class:'btn btn-primary' %>
	<%=link_to "Cancel", admin_users_path, class:'btn btn-default' %>
<% end %>

app/views/admin/users/show.html.erb
<h1>Admin::Users#show</h1>
<p>Find me in app/views/admin/users/show.html.erb</p>